# Generated by Django 4.2.13 on 2024-07-17 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planet',
            old_name='size',
            new_name='radius',
        ),
        migrations.RenameField(
            model_name='satellite',
            old_name='size',
            new_name='radius',
        ),
    ]
